# Generated by Django 3.2.7 on 2021-09-18 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20210918_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialization',
            name='department',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='user.department'),
            preserve_default=False,
        ),
    ]
