# Generated by Django 3.2.7 on 2021-09-19 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_studentregistration_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentregistration',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=15, null=True),
        ),
    ]
