# Generated by Django 3.2.7 on 2021-09-19 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_studentregistration_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentregistration',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
